/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "../Drivers/Inc/stm32f401xx.h"
#include "../Drivers/Inc/stm32f401xx_gpio_driver.h"
#include "../Drivers/Inc/stm32f401xx_spi_driver.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


/*************************************\
  
  PA10 -> Gpio button, connect to GND over the button
  PA15 -> Gpio Led, connect to GND
  
\*************************************/

typedef struct {
    SPI_Handle SpiHandle;
    GPIO_Handle NssPin;
    GPIO_Handle SckPin;
    GPIO_Handle MisoPin;
    GPIO_Handle MosiPin;
} SPI;

GPIO_Handle buttonPin = (GPIO_Handle){
    .pGPIOx = GPIOA,
    .Config = (GPIO_Config){
        .PinNumber = 10,
        .PinMode = GPIO_PINMODE_INPUT,
        .PupdCtrl = GPIO_PUPDCTRL_PULLUP,
        .RtFtDetect = GPIO_RTFTDETECT_FT
    }
};

u8 isButtonPressed = FALSE;

int main(void)
{
    SPI SPI_Display = (SPI){
        .SpiHandle = (SPI_Handle){
            .pSPIx = SPI1,
            .Config = (SPI_Config){
                .BusConfig = SPI_BUSCONFIG_FULLDUPLEX,
                .BitOrder = SPI_BITORDER_LSBFIRST,
                .CPHA = SPI_CPHA_FIRSTEDGE,
                .CPOL = SPI_CPOL_LOW,
                .DeviceMode = SPI_DEVICEMODE_MASTER,
                .SclkSpeed = SPI_SCLKSPEED_DIV2,
                .SSM = SPI_SSM_HARDWARE,
                .DFF = SPI_DFF_8BIT
            }
        },
        .NssPin = (GPIO_Handle){
            .pGPIOx = GPIOA,
            .Config = (GPIO_Config){
                .PinNumber = 4,
                .PinMode = GPIO_PINMODE_ALTFUN,
                .AltFunNumber = 5,
                .OpSpeed = GPIO_OPSPEED_LOW,
                .OpType = GPIO_OPTYPE_PP,
                .PupdCtrl = GPIO_PUPDCTRL_NOPUPD,
                .RtFtDetect = GPIO_RTFTDETECT_NONE
            }
        },
        .SckPin = (GPIO_Handle){
            .pGPIOx = GPIOA,
            .Config = (GPIO_Config){
                .PinNumber = 5,
                .PinMode = GPIO_PINMODE_ALTFUN,
                .AltFunNumber = 5,
                .OpSpeed = GPIO_OPSPEED_HIGH,
                .OpType = GPIO_OPTYPE_PP,
                .PupdCtrl = GPIO_PUPDCTRL_NOPUPD,
                .RtFtDetect = GPIO_RTFTDETECT_NONE
            }
        },
        .MisoPin = (GPIO_Handle){
            .pGPIOx = GPIOA,
            .Config = (GPIO_Config){
                .PinNumber = 6,
                .PinMode = GPIO_PINMODE_ALTFUN,
                .AltFunNumber = 5,
                .OpSpeed = GPIO_OPSPEED_HIGH,
                .OpType = GPIO_OPTYPE_PP,
                .PupdCtrl = GPIO_PUPDCTRL_NOPUPD,
                .RtFtDetect = GPIO_RTFTDETECT_NONE
            }
        },
        .MosiPin = (GPIO_Handle){
            .pGPIOx = GPIOA,
            .Config = (GPIO_Config){
                .PinNumber = 7,
                .PinMode = GPIO_PINMODE_ALTFUN,
                .AltFunNumber = 5,
                .OpSpeed = GPIO_OPSPEED_HIGH,
                .OpType = GPIO_OPTYPE_PP,
                .PupdCtrl = GPIO_PUPDCTRL_NOPUPD,
                .RtFtDetect = GPIO_RTFTDETECT_NONE
            }
        }
    };

    GPIO_Handle DisplaySelectPin = (GPIO_Handle){
        .pGPIOx = GPIOA,
        .Config = (GPIO_Config){
            .PinNumber = 1,
            .PinMode = GPIO_PINMODE_OUTPUT,
            .OpSpeed = GPIO_OPSPEED_MED,
            .OpType = GPIO_OPTYPE_PP,
            .RtFtDetect = GPIO_RTFTDETECT_NONE
            
        }
    };
    
    float temperatureData = 0;
    
    IRQ_ItCtrl(IRQ_NO_EXTI15_10, ENABLE);
    GPIO_Init(&buttonPin);
    GPIO_Init(&DisplaySelectPin);
    GPIO_Init(&SPI_Display.SckPin);
    GPIO_Init(&SPI_Display.NssPin);
    GPIO_Init(&SPI_Display.MisoPin);
    GPIO_Init(&SPI_Display.MosiPin);
    SPI_Init(&SPI_Display.SpiHandle);
    
    GPIO_WritePin(&DisplaySelectPin, HIGH);
    
    while (TRUE)
    {
        if (isButtonPressed)
        {
            isButtonPressed = FALSE;
            GPIO_WritePin(&DisplaySelectPin, LOW);
            // implement rest of the logic here
            GPIO_WritePin(&DisplaySelectPin, HIGH);
        }
    }
}

void EXTI15_10_IRQHandler(void)
{
    GPIO_IRQHandled(10, 15);
}

void GPIO_AppEventCallback(u8 pinNumber)
{
    if (pinNumber == buttonPin.Config.PinNumber)
        isButtonPressed = TRUE;
}